production:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUD_API_KEY"] %>
  api_secret: <%= ENV["CLOUD_API_SECRET"] %>
  secure: true
  cdn_subdomain: true

development: 
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["API_KEY"] %>
  api_secret: <%= ENV["API_SECRET"] %>
  secure: true
  cdn_subdomain: true